name: turf_pip
description: A small library for detecting if a point lies inside a polygon
version: 0.0.1
repository: https://github.com/dartclub/turf_pip

environment:
  sdk: ">=2.17.1 <3.0.0"

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.19.3
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  analyzer: ^2.7.0
  benchmark: ^0.3.0

dependencies:
  turf: ^0.0.6